### ISSUE TITLE
Separate document content from presentation

### ISSUE THREAD

**Issue by nemtsov** [dowjones/intentionjs#36]
Hey guys, what do you think of the idea of extracting intention's attributes into an intent-sheet?

Just as we first had styles in the document, and then extracted them into stylesheets to separate the document content from its presentation, I think it may make sense to also extract the intent attributes to get the same benefits here.

Here's a before / after examples:

Before:

``` html
<body>
   <header>
      <img intent
         in-standard-src="med.png"
         in-mobile-src="small.png" />
   </header>
   <nav intent
      in-abovethefold-after="header"
      in-belowthefold-prepend="body"
      in-belowthefold-class="sticky">
   </nav>
   <section intent
      in-daytime-class="light"
      in-nighttime-class="dark">
         Hello, World!
   </section>

   <script>
      intent.on('nighttime', function() {
         $('section').text("Goodnight, World!");
      });
   </script>
</body>
```

After:

`index.html`

``` html
<head>
  <link rel="intentsheet" type="text/intent" href="/assets/intent/simple.intent" />
</head>
<body>
  <header>
    <img />
  </header>

  <nav>
  </nav>

  <section class="main">
    Hello, World!
  </section>

  <script>
    intent.on('nighttime', function() {
      $('section').text("Goodnight, World!");
    });
  </script>
</body>
```

`simple.intent`

``` css
header > img {
  standard-src: "med.png"
  mobile-src: "med.png"
}

nav {
  abovethefold-after: header
  belowthefold-prepend: body
  belowthefold-class: sticky
}

.main {
  daytime-class: light
  nighttime-class: dark
}
```

What do you think?
